create extension if not exists pgcrypto;
create type public.listing_status as enum ('pending','active','rejected','suspended');
create type public.bid_status as enum ('pending','completed','failed','refunded','cancelled');

create table public.categories (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, description text, created_at timestamptz not null default now());
create table public.listings (id uuid primary key default gen_random_uuid(), slug text unique not null, name text not null, website_url text unique not null, normalized_domain text unique not null, short_description text, long_description text, logo_url text, og_image_url text, category_id uuid references public.categories(id), status public.listing_status not null default 'pending', total_bid_cents bigint not null default 0 check(total_bid_cents >= 0), total_clicks bigint not null default 0, total_impressions bigint not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), last_bid_at timestamptz);
create table public.bids (id uuid primary key default gen_random_uuid(), listing_id uuid not null references public.listings(id), amount_cents bigint not null check(amount_cents > 0), currency text not null default 'USD', payment_id uuid, provider text not null, status public.bid_status not null default 'pending', created_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(), provider text not null, provider_order_id text unique not null, provider_capture_id text unique, listing_id uuid not null references public.listings(id), bid_id uuid references public.bids(id), amount_cents bigint not null, currency text not null default 'USD', status public.bid_status not null default 'pending', payer_email text, raw_metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), completed_at timestamptz);
alter table public.bids add constraint bids_payment_fk foreign key(payment_id) references public.payments(id);
create table public.clicks (id bigint generated always as identity primary key, listing_id uuid not null references public.listings(id), created_at timestamptz not null default now(), referrer text, country text, device_category text);
create table public.rank_snapshots (id bigint generated always as identity primary key, listing_id uuid not null references public.listings(id), rank integer not null check(rank > 0), scope text not null default 'overall', captured_at timestamptz not null default now());
create index listings_active_rank_idx on public.listings(total_bid_cents desc) where status = 'active'; create index listings_category_rank_idx on public.listings(category_id,total_bid_cents desc) where status = 'active'; create index bids_listing_created_idx on public.bids(listing_id,created_at desc); create index clicks_listing_created_idx on public.clicks(listing_id,created_at desc);
alter table public.categories enable row level security; alter table public.listings enable row level security; alter table public.bids enable row level security; alter table public.payments enable row level security; alter table public.clicks enable row level security; alter table public.rank_snapshots enable row level security;
create policy "public reads active listings" on public.listings for select using(status='active'); create policy "public reads categories" on public.categories for select using(true); create policy "public reads completed bids" on public.bids for select using(status='completed'); create policy "public reads rank history" on public.rank_snapshots for select using(true);

create or replace function public.apply_completed_bid(p_payment_id uuid) returns void language plpgsql security definer set search_path = public as $$ declare v_payment public.payments%rowtype; begin select * into v_payment from payments where id=p_payment_id for update; if not found then raise exception 'payment not found'; end if; if v_payment.status='completed' then return; end if; update payments set status='completed',completed_at=now(),updated_at=now() where id=p_payment_id; update bids set status='completed' where id=v_payment.bid_id; update listings set total_bid_cents=total_bid_cents+v_payment.amount_cents,last_bid_at=now(),updated_at=now(),status='active' where id=v_payment.listing_id; end; $$;
revoke all on function public.apply_completed_bid(uuid) from public, anon, authenticated;
